### ISSUE TITLE
Detect exceptions documentation differences

### ISSUE THREAD

**Issue by PumpkinSeed** [banzaicloud/logging-operator-docs#19]
**Describe the bug**
There are two kind of descriptors of the detectExceptions. Once it represented as an array in filters, once it's an element of the filters.spec.

![Screenshot from 2020-04-21 20-42-27](https://user-images.githubusercontent.com/5867522/79901785-acb35b00-8410-11ea-94a1-820c2984f861.png)
![Screenshot from 2020-04-21 20-42-41](https://user-images.githubusercontent.com/5867522/79901790-ae7d1e80-8410-11ea-9099-17ffc7a65daf.png)

**Comment by pepov** [comment]
Thanks for pointing out and sorry for the delay! This will be fixed with the next release.
