### ISSUE TITLE
small doc nitpick s/elasticsearch/kafka/g

### ISSUE THREAD

**Issue by jdonnelly-apixio** [banzaicloud/logging-operator-docs#33]
**Describe the bug**
Doc says `Elasticsearch` instead of `kafka`.

```
Create an Elasticsearch output definition.
```

**Steps to reproduce the issue:**
Go to https://banzaicloud.com/docs/one-eye/logging-operator/quickstarts/kafka-nginx/

**Expected behavior**
It should say kafka.

**Comment by fekete-robert** [comment]
Thanks a lot for the report, fixed in https://github.com/banzaicloud/logging-operator-docs/pull/34
