### ISSUE TITLE
File not found "master/docs/deploy/manifests/rbac.yaml"

### ISSUE THREAD

**Issue by AnicDominic** [banzaicloud/logging-operator-docs#47]
The links are not working

Deploy the Logging operator from Kubernetes Manifests >
Create a ServiceAccount and install cluster roles >
https://raw.githubusercontent.com/banzaicloud/logging-operator-docs/master/docs/deploy/manifests/rbac.yaml -> Error 404 File not found

Could you please double check the links?

**Comment by fekete-robert** [comment]
Hi, many thanks for the report, it should be:

**Comment by AnicDominic** [comment]
Thank you for your quick feedback. Looks like this file has an error. I get the following message:
`kubectl -n logging create -f https://raw.githubusercontent.com/banzaicloud/logging-operator-docs/master/docs/install/manifests/rbac.yaml
serviceaccount/logging-operator created
clusterrole.rbac.authorization.k8s.io/logging-operator created
error: error parsing https://raw.githubusercontent.com/banzaicloud/logging-operator-docs/master/docs/install/manifests/rbac.yaml: error converting YAML to JSON: yaml: line 2: mapping values are not allowed in this context
`

**Comment by fekete-robert** [comment]
Seems there was some invalid content in the file, probably because of a search/replace gone haywire :) Can you try it with this file? https://raw.githubusercontent.com/banzaicloud/logging-operator-docs/82a4607ad9c53c37ba74b614db9252251df961a2/docs/install/manifests/rbac.yaml
